memo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('myMemo.urls', namespace='memo')),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
]

myMemo/urls.py
from django.conf.urls import url
from . import views
from django.views.static import serve
from django.contrib.auth.decorators import login_required
from django.conf import settings

urlpatterns = [
	url(r'^sign/$', views.SignForm.as_view(), name='signForm'),
	url(r'^login/$', views.LoginForm.as_view(), name='loginForm'),
	url(r'^logout/$', views.logout, name='logout'),
	url(r'^auth/$', views.Auth.as_view(), name='auth'),
	url(r'^memo/$', views.myMemo, name='myMemo'),
	url(r'^random/$', views.randomMemo, name='randomMemo'),
]


myMemo/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.conf import settings 

class MyUser(AbstractUser):
	pass

class PublicMemo(models.Model):
	title = models.TextField()
	text = models.TextField()
	time = models.DateTimeField(default=timezone.now)
	owner = models.ForeignKey(MyUser)

class PrivateMemo(models.Model):
	title = models.TextField()
	text = models.TextField()
	time = models.DateTimeField(default=timezone.now)
	owner = models.ForeignKey(MyUser)
	
	

          

myMemo/views.py
from django.shortcuts import render
from django.views.generic import View
from django.utils import timezone
from .models import MyUser
from .models import PublicMemo
from .models import PrivateMemo
from django.views.generic.base import TemplateView
from django.contrib.auth import authenticate, login, logout as _logout

class Auth(TemplateView):
	template_name='myMemo/auth.html'

class SignForm(View):
	def get(self, request, *args, **kwargs):
		response = render(request, 'myMemo/signForm.html')
		return response
	
	def post(self, request, *args, **kwargs):
		user_id = request.POST.get('user_id')
		user_pw = request.POST.get('user_pw')
		user_pwagain = request.POST.get('user_pwagain')
		user_email = request.POST.get('user_email')

		if user_pw is not user_pwagain:
			msg = "Password and Password Again is Incorrect"
			return render(request, 'myMemo/auth.html' , {'msg':msg})

		try:
			user_model = MyUser.objects.create(username=user_id, email=user_email)
			user_model.set_password(user_pw)
			user_model.save()
			msg = "Succese to Make Account"
		except:
			msg = "This is already a registered ID."
			return render(request, 'myMemo/auth.html', {'msg':msg} )

		return render(request, 'myMemo/auth.html' , {'msg':msg})

class LoginForm(View):
	def get(self, request, *args, **kwargs):
		response = render(request, 'myMemo/loginForm.html')
		return response

	def post(self, request, *args, **kwargs):
		user_id = request.POST.get('user_id')
		user_pw = request.POST.get('user_pw')
		user = authenticate(username=user_id, password=user_pw)

		if user is not None:
			login(request, user)
			return render(request, 'myMemo/memo.html')
		else:	
			msg = "Invalid ID or PW."
			return render(request, 'myMemo/auth.html', {'msg':msg})

def logout(request):
	_logout(request)
	return render(request, 'myMemo/auth.html')

def registerMemo(request):
	private = request.POST['private']
	title = request.POST['title']
	text = request.POST['text']
	user = request.user

	if private is "private":	
		privateMemo = PrivateMemo(title=title, text=text, time=timezone.now(), owner=user)
		privateMemo.save()
		return render(request, 'myMemo/index.html')

	else:
		publicMemo = PublicMemo(title=title, text=text, time=timezone.now(), owner=user)
		publicMemo.save()
		return render(request, 'myMemo/index.html')
	


def myMemo(request):
	user = request.user
	try:
		publicMemos = PublicMemo.objects.filter(owner=user)
		privateMemos = PrivateMemo.objects.filter(owner=user)
	except:
		publicMemos = None
		privateMemos = None

	return render(request, 'myMemo/memo.html',{'publicMemos':publicMemos, 'privateMemos':privateMemos})

def randomMemo(request):
	randomMemo = PublicMemo.objects.order_by('?').first()
	return render(request, 'myMemo/random.html', {'randomMemo':randomMemo})

myMemo/templates/myMemo/auth.html
{% load staticfiles %}
<html>
    <script src="{% static 'js/jquery.min.js' %}" ></script>
    <script src="{% static 'js/jquery-ui.min.js' %}" ></script>
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" >
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <script>
      $(document).ready(function(){
        $('#content').delay(200).animate({opacity: 1}, {duration: 1000});
        viewPage('/user/login');
      });
      $(window).resize(function() {
      });

      function viewPage(url){
        $('#viewer').animate({opacity: 0}, {complete: function() {
          $.ajax({
              url: url,
              success:function(data){
                $('#viewer').html(data);
              }
          })

          $('#viewer').animate({opacity: 1}, {duration: 500});
        },duration: 500});
      }
    </script>

    <style>
      * {
        font-family: 'Open Sans', sans-serif;
        font-size: 26pt;
        color: white;
        padding: 0px;
        margin: 0px;
      }
      #blind {
        position: absolute;
        width: 100%;
        height: 100%;
        background: #000000;
      }
      #content {
        width: 100%;
        height: 100%;

        position: relative;
        opacity: 0;

        background-size: cover;
        background-image: url({% static 'img/background.png' %});
      }
      #lens{
        width: 100%;
        height: 100%;

        background-image: -webkit-gradient(linear, 50% 0%, 50% 100%, color-stop(20%, rgba(0, 0, 0, 0.08)), color-stop(59%, rgba(0, 0, 0, 0.08)), color-stop(100%, rgba(0, 0, 0, 0.8)));
        background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0.08) 20%, rgba(0, 0, 0, 0.08) 40%, rgba(0, 0, 0, 0.7) 100%);
        background-image: -webkit-linear-gradient(top, rgba(0, 0, 0, 0.08) 20%, rgba(0, 0, 0, 0.08) 40%, rgba(0, 0, 0, 0.7) 100%);
        background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.08) 20%, rgba(0, 0, 0, 0.08) 40%, rgba(0, 0, 0, 0.7) 100%);
      }

      input[type="text"], input[type="password"] {
        color: white;
        background: #444444;
        font-size: 12pt;
        width: 100%;
        opacity: 0.6;
        appearance: none;
        box-shadow: none;
        -moz-border-radius: 7px;
        border-radius: 7px;
        border: none;
        padding:5px;
        padding-left: 10px;
        padding-right: 10px;
      }

      input[type="button"], input[type="submit"] {
        color: black;
        background: #AAAAAA;
        opacity: 0.5;
        font-size: 12pt;
        appearance: none;
        box-shadow: none;
        -moz-border-radius: 7px;
        border-radius: 7px;
        border: none;
        padding:5px;
        padding-left: 10px;
        padding-right: 10px;
      }
    </style>
  </head>
  <body>
    <div>
      <div id="blind">
      </div>
      <div id="content">
        <div id="lens">
          <div id="viewer">

          </div>
        </div>
      </div>
    </div>
  </body>
</html>

myMemo/templates/myMemo/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
Hello {{user}}

	<form name="publicMemo" action={% url 'memo:privateMemo' %} method="POST">{% csrf_token %}
		<div class="form-group">
		    <input type="text" class="form-control login-field" value="" placeholder="Title" name="title" />
		</div>
		<div class="form-group">
			<input type="text" class="form-control login-field" value="" placeholder="Text" name="text"  />
		</div>
		<button type="submit" class="btn btn-warning btn-lg btn-block" style="margin-top: 40px; ">저장</button>
	</form>

private : {{ privateMemos }}<br>

public : {{ publicMemos }}

</body>
</html>

myMemo/templates/myMemo/loginForm.html
{% load staticfiles %}
<form action={% url 'memo:loginForm' %} method="POST">{% csrf_token %}
	<table style="padding-top: 25%; text-align: center; margin: auto">
	  <tr>
	    <td><input name="user_id" tabindex="1" style="height: 35px" type="text" placeholder="Identity"/><br></td>
	    <td rowspan="2">
	      <input tabindex="3" style="height: 79px; width: 100px; margin-left: 8px" type="submit" value="Login"/>
	    </td>
	  </tr>
	  <tr>
	    <td><input name="user_pw" tabindex="2" style="margin-top: 5px; height: 35px" type="password" placeholder="Password"/></td>
	  </tr>
	  <tr>
	    <td>
	      <pre tabindex="4" style="width: 100%; text-align: right; opacity: 0.3; font-size: 8pt" onclick="viewPage('/user/sign');">You don't have a account?</pre>
	    </td>
	    <td></td>
	  </tr>
	</table>
</form>

myMemo/templates/myMemo/memo.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

{% for privateMemo in privateMemos %}
private;{{ privateMemo.title }};{{ privateMemo.text }}<br>
{% endfor %}
{% for publicMemo in publicMemos %}
public;{{ publicMemo.title }};{{ publicMemo.text }}<br>
{% endfor %}

</body>
</html>

myMemo/templates/myMemo/random.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
random;{{randomMemo.title}};{{randomMemo.text}};{{randomMemo.time}}
</body>
</html>

myMemo/templates/myMemo/signForm.html
{% load staticfiles %}
{{ error }}
{{ userid }}
<form action={% url 'memo:signForm' %} method="POST">{% csrf_token %}
	<table style="padding-top: 20%; text-align: center; margin: auto">
	  <tr>
	    <td><input name="user_id" tabindex="1" style="height: 35px" type="text" placeholder="Identity"/></td>
	  </tr>
	  <tr>
	    <td><input name="user_email" tabindex="2" style="margin-top: 5px; height: 35px" type="text" placeholder="Email"/></td>
	  </tr>
	  <tr>
	    <td><input name="user_pw" tabindex="3" style="margin-top: 10px; height: 35px" type="password" placeholder="Password"/></td>
	  </tr>
	  <tr>
	    <td><input name="user_pwagain" tabindex="4" style="margin-top: 10px; height: 35px" type="password" placeholder="Password Again"/></td>
	  </tr>
	  <tr>
	    <td><input tabindex="5" style="margin-top: 15px; width: 100%;" type="submit" value="Sign"/></td>
	  </tr>
	  <tr>
	    <td>
	      <pre style="width: 100%; text-align: right; opacity: 0.3; font-size: 8pt" onclick="viewPage('/user/login');">Already have a account</pre>
	    </td>
	  </tr>
	</table>
</form>